#!/usr/bin/env python3
"""
Production-ready Flask server for GraceAI backend
Configured for AWS deployment with Supabase integration
"""

import os
from flask import Flask, request, jsonify
from flask_cors import CORS
import tempfile
import shutil
from werkzeug.utils import secure_filename
import subprocess
import json
import sys
import uuid
from datetime import datetime
import logging
from dotenv import load_dotenv
from supabase import create_client, Client

# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)
CORS(app)

# Environment configuration
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')
DEBUG = ENVIRONMENT == 'development'

# File upload configuration
UPLOAD_FOLDER = os.getenv('UPLOAD_FOLDER', 'uploads')
MAX_CONTENT_LENGTH = int(os.getenv('MAX_CONTENT_LENGTH', 50 * 1024 * 1024))  # 50MB

if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['MAX_CONTENT_LENGTH'] = MAX_CONTENT_LENGTH

# Supabase configuration
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_KEY = os.getenv('SUPABASE_KEY')

# Initialize Supabase client
if SUPABASE_URL and SUPABASE_KEY:
    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
    logger.info("Supabase client initialized successfully")
else:
    supabase = None
    logger.warning("Supabase credentials not found - running in local mode")

# Add the current directory to Python path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Cloud Music Processing Functions
def process_sheet_music_with_audiveris(image_path, output_dir):
    """Process sheet music using cloud-installed Audiveris"""
    try:
        logger.info(f"Processing sheet music with Audiveris: {image_path}")
        
        # Use cloud-installed Audiveris
        audiveris_cmd = [
            "java", "-jar", "/usr/local/bin/audiveris.jar",
            "-batch",
            "-output", output_dir,
            image_path
        ]
        
        logger.info(f"Running Audiveris command: {' '.join(audiveris_cmd)}")
        result = subprocess.run(audiveris_cmd, capture_output=True, text=True, check=True, timeout=300)
        
        logger.info(f"Audiveris processing completed successfully")
        logger.info(f"Audiveris stdout: {result.stdout}")
        
        # Look for generated files
        base_name = os.path.splitext(os.path.basename(image_path))[0]
        omr_path = os.path.join(output_dir, f"{base_name}.omr")
        musicxml_path = os.path.join(output_dir, f"{base_name}.mxl")
        
        if os.path.exists(omr_path):
            logger.info(f"Found OMR file: {omr_path}")
            return omr_path
        elif os.path.exists(musicxml_path):
            logger.info(f"Found MusicXML file: {musicxml_path}")
            return musicxml_path
        else:
            # Look for any generated files
            for file in os.listdir(output_dir):
                if file.endswith(('.omr', '.mxl', '.xml')):
                    found_path = os.path.join(output_dir, file)
                    logger.info(f"Found generated file: {found_path}")
                    return found_path
            
            raise FileNotFoundError("No output files generated by Audiveris")
        
    except subprocess.CalledProcessError as e:
        logger.error(f"Audiveris processing failed: {e}")
        logger.error(f"Audiveris stderr: {e.stderr}")
        raise
    except subprocess.TimeoutExpired:
        logger.error("Audiveris processing timed out")
        raise
    except Exception as e:
        logger.error(f"Error in Audiveris processing: {e}")
        raise

def convert_musicxml_with_musescore(musicxml_path, output_dir):
    """Convert MusicXML to MIDI using cloud-installed MuseScore"""
    try:
        logger.info(f"Converting MusicXML to MIDI with MuseScore: {musicxml_path}")
        
        # Generate output MIDI path
        base_name = os.path.splitext(os.path.basename(musicxml_path))[0]
        midi_path = os.path.join(output_dir, f"{base_name}.mid")
        
        # Use cloud-installed MuseScore
        musescore_cmd = [
            "musescore3",
            "--export-to", midi_path,
            musicxml_path
        ]
        
        logger.info(f"Running MuseScore command: {' '.join(musescore_cmd)}")
        result = subprocess.run(musescore_cmd, capture_output=True, text=True, check=True, timeout=300)
        
        logger.info(f"MuseScore conversion completed successfully")
        logger.info(f"MuseScore stdout: {result.stdout}")
        
        if os.path.exists(midi_path):
            logger.info(f"MIDI file created: {midi_path}")
            return midi_path
        else:
            raise FileNotFoundError("MIDI file not found after MuseScore conversion")
        
    except subprocess.CalledProcessError as e:
        logger.error(f"MuseScore conversion failed: {e}")
        logger.error(f"MuseScore stderr: {e.stderr}")
        raise
    except subprocess.TimeoutExpired:
        logger.error("MuseScore conversion timed out")
        raise
    except Exception as e:
        logger.error(f"Error in MuseScore conversion: {e}")
        raise

def process_sheet_music_pipeline(image_path, output_dir):
    """Complete sheet music processing pipeline: Image -> MusicXML -> MIDI"""
    try:
        logger.info(f"Starting sheet music processing pipeline for: {image_path}")
        
        # Step 1: Process image with Audiveris
        logger.info("Step 1: Processing image with Audiveris...")
        audiveris_output = process_sheet_music_with_audiveris(image_path, output_dir)
        
        # Step 2: Convert to MIDI with MuseScore
        logger.info("Step 2: Converting to MIDI with MuseScore...")
        midi_path = convert_musicxml_with_musescore(audiveris_output, output_dir)
        
        logger.info(f"Sheet music processing pipeline completed successfully: {midi_path}")
        return midi_path
        
    except Exception as e:
        logger.error(f"Sheet music processing pipeline failed: {e}")
        raise

def upload_file_to_supabase(file, user_id, file_type):
    """Upload file to Supabase Storage"""
    try:
        if not supabase:
            logger.warning("Supabase not configured - skipping file upload")
            return None, None
            
        # Determine bucket based on file type
        if file_type == 'audio':
            bucket_name = 'user-audio'
        elif file_type == 'sheet_music':
            bucket_name = 'user-sheet-music'
        else:
            bucket_name = 'analysis-results'
            
        # Generate unique filename
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"{user_id}/{file_type}_{timestamp}_{secure_filename(file.filename)}"
        
        logger.info(f"Attempting to upload {file_type} file to bucket '{bucket_name}': {filename}")
        
        # Fix MIME type detection for PDFs
        content_type = file.content_type
        if file.filename.lower().endswith('.pdf'):
            content_type = 'application/pdf'
        elif file.filename.lower().endswith('.m4a'):
            content_type = 'audio/mp4'
        
        # Upload to Supabase Storage
        response = supabase.storage.from_(bucket_name).upload(
            path=filename,
            file=file.read(),
            file_options={"content-type": content_type}
        )
        
        # Get public URL
        file_url = supabase.storage.from_(bucket_name).get_public_url(filename)
        
        logger.info(f"File uploaded to Supabase bucket '{bucket_name}': {filename}")
        return file_url, filename
    except Exception as e:
        logger.error(f"Error uploading to Supabase: {str(e)}")
        logger.error(f"Error type: {type(e).__name__}")
        logger.error(f"Error details: {str(e)}")
        return None, None

def save_session_to_supabase(session_data):
    """Save practice session to Supabase database"""
    try:
        if not supabase:
            logger.warning("Supabase not configured - skipping session save")
            return None
            
        response = supabase.table('practice_sessions').insert(session_data).execute()
        saved_session = response.data[0] if response.data else None
        logger.info(f"Session saved to Supabase: {saved_session['id'] if saved_session else 'None'}")
        return saved_session
    except Exception as e:
        logger.error(f"Error saving session to Supabase: {str(e)}")
        return None

def update_user_stats(user_id, session_data):
    """Update user statistics in Supabase"""
    try:
        if not supabase:
            logger.warning("Supabase not configured - skipping stats update")
            return
            
        # Get current user stats
        response = supabase.table('user_profiles').select('*').eq('id', user_id).execute()
        current_stats = response.data[0] if response.data else {}
        
        # Calculate new stats
        new_total_sessions = current_stats.get('total_sessions', 0) + 1
        new_total_practice_time = current_stats.get('total_practice_time', 0) + session_data.get('duration', 0)
        
        # Update user profile
        supabase.table('user_profiles').upsert({
            'id': user_id,
            'total_sessions': new_total_sessions,
            'total_practice_time': new_total_practice_time,
            'average_accuracy': session_data.get('accuracy', 0),  # Will be calculated by trigger
            'best_accuracy': max(current_stats.get('best_accuracy', 0), session_data.get('accuracy', 0))
        }).execute()
        
        logger.info(f"User stats updated for user: {user_id}")
        
    except Exception as e:
        logger.error(f"Error updating user stats: {str(e)}")

def validate_file_type(filename, allowed_extensions):
    """Validate file type based on extension"""
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in allowed_extensions

def validate_file_size(file_size, max_size):
    """Validate file size"""
    return file_size <= max_size

@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint"""
    return jsonify({
        'status': 'healthy',
        'environment': ENVIRONMENT,
        'timestamp': datetime.utcnow().isoformat()
    })

@app.route('/analyze', methods=['POST'])
def analyze():
    """Analyze performance endpoint with Supabase integration"""
    try:
        # Validate request
        if 'audio_file' not in request.files or 'sheet_music' not in request.files:
            return jsonify({'error': 'Missing required files'}), 400
        
        audio_file = request.files['audio_file']
        sheet_music_file = request.files['sheet_music']
        user_id = request.form.get('user_id')
        
        if not user_id:
            return jsonify({'error': 'Missing user_id'}), 400
        
        # Validate file types
        if not validate_file_type(audio_file.filename, ['m4a', 'wav', 'mp3']):
            return jsonify({'error': 'Invalid audio file type'}), 400
        
        if not validate_file_type(sheet_music_file.filename, ['pdf', 'jpg', 'jpeg', 'png', 'heic']):
            return jsonify({'error': 'Invalid sheet music file type'}), 400
        
        # Validate file sizes
        if not validate_file_size(len(audio_file.read()), MAX_CONTENT_LENGTH):
            return jsonify({'error': 'Audio file too large'}), 400
        
        audio_file.seek(0)  # Reset file pointer
        
        if not validate_file_size(len(sheet_music_file.read()), MAX_CONTENT_LENGTH):
            return jsonify({'error': 'Sheet music file too large'}), 400
        
        sheet_music_file.seek(0)  # Reset file pointer
        
        # Create temporary files
        with tempfile.NamedTemporaryFile(delete=False, suffix='.m4a', dir=UPLOAD_FOLDER) as audio_temp:
            audio_file.save(audio_temp.name)
            audio_path = audio_temp.name
        
        with tempfile.NamedTemporaryFile(delete=False, suffix='.pdf', dir=UPLOAD_FOLDER) as sheet_temp:
            sheet_music_file.save(sheet_temp.name)
            sheet_path = sheet_temp.name
        
        try:
            # Upload files to Supabase Storage
            logger.info(f"Uploading files to Supabase for user: {user_id}")
            
            audio_url, audio_filename = upload_file_to_supabase(audio_file, user_id, 'audio')
            sheet_music_url, sheet_music_filename = upload_file_to_supabase(sheet_music_file, user_id, 'sheet_music')
            
            if not audio_url or not sheet_music_url:
                logger.error("Failed to upload files to Supabase")
                return jsonify({'error': 'Failed to upload files'}), 500
            
            # Run analysis pipeline
            logger.info(f"Starting analysis for user: {user_id}")
            
            # Create output directory for processing
            output_dir = os.path.join(UPLOAD_FOLDER, f"analysis_{user_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}")
            os.makedirs(output_dir, exist_ok=True)
            
            # Process sheet music with cloud-installed tools
            logger.info("Processing sheet music with Audiveris and MuseScore...")
            try:
                sheet_midi_path = process_sheet_music_pipeline(sheet_path, output_dir)
                logger.info(f"Sheet music processed successfully: {sheet_midi_path}")
            except Exception as e:
                logger.error(f"Sheet music processing failed: {e}")
                # Fallback to audio-only analysis
                sheet_midi_path = None
            
            # Process audio with Basic Pitch
            logger.info("Processing audio with Basic Pitch...")
            try:
                from transcriber import transcribe_audio
                audio_midi_path = transcribe_audio(audio_path, output_dir)
                logger.info(f"Audio processed successfully: {audio_midi_path}")
            except Exception as e:
                logger.error(f"Audio processing failed: {e}")
                return jsonify({'error': 'Audio processing failed'}), 500
            
            # Run comparison analysis if both MIDI files exist
            if sheet_midi_path and audio_midi_path:
                logger.info("Running MIDI comparison analysis...")
                try:
                    from midi_comparison import compare_midi_files
                    analysis_data = compare_midi_files(sheet_midi_path, audio_midi_path)
                    success = True
                except Exception as e:
                    logger.error(f"MIDI comparison failed: {e}")
                    success = False
            else:
                logger.warning("Skipping MIDI comparison - missing sheet music MIDI")
                # Create basic analysis data for audio-only
                analysis_data = {
                    'accuracy': 0.0,
                    'correct_notes': 0,
                    'total_notes': 0,
                    'missed_notes': [],
                    'tempo_feedback': 'Sheet music processing unavailable',
                    'timing_feedback': 'Sheet music processing unavailable'
                }
                success = True
            
            if success:
                # Read analysis results
                import glob
                # Look for report files in the parent directory's generated_files folder
                parent_dir = os.path.dirname(os.path.dirname(__file__))
                report_files = glob.glob(os.path.join(parent_dir, 'generated_files', 'performance_report_*.json'))
                
                if report_files:
                    latest_report = max(report_files, key=os.path.getctime)
                    with open(latest_report, 'r') as f:
                        analysis_data = json.load(f)
                    
                    logger.info(f"Analysis data loaded: {analysis_data}")
                    
                    # Format results for API response - use actual data, not fallbacks
                    analysis_result = {
                        'accuracy': analysis_data.get('accuracy'),
                        'correctNotes': analysis_data.get('correct_notes'),
                        'totalNotes': analysis_data.get('total_notes'),
                        'missedNotes': analysis_data.get('missed_notes'),
                        'tempoFeedback': analysis_data.get('tempo_feedback'),
                        'timingFeedback': analysis_data.get('timing_feedback')
                    }
                    
                    # Validate that we have real data
                    if analysis_result['accuracy'] is None:
                        logger.error("No accuracy data found in analysis results")
                        return jsonify({'error': 'Analysis results incomplete'}), 500
                    
                    logger.info(f"Formatted analysis result: {analysis_result}")
                    
                    # Prepare session data for Supabase - match iOS app expectations
                    session_data = {
                        'user_id': user_id,
                        'date': datetime.now().isoformat(),  # iOS expects 'date' not 'created_at'
                        'audio_file_name': os.path.basename(audio_url) if audio_url else 'unknown_audio.m4a',
                        'sheet_music_file_name': os.path.basename(sheet_music_url) if sheet_music_url else 'unknown_sheet.pdf',
                        'piece_title': request.form.get('piece_title', ''),
                        'duration': float(request.form.get('duration', 0.0)),
                        'accuracy': analysis_result['accuracy'],
                        'correct_notes': analysis_result['correctNotes'],
                        'total_notes': analysis_result['totalNotes'],
                        'missed_notes': ','.join(analysis_result['missedNotes']) if isinstance(analysis_result['missedNotes'], list) else str(analysis_result['missedNotes']),
                        'tempo_feedback': analysis_result['tempoFeedback'],
                        'timing_feedback': analysis_result['timingFeedback']
                    }
                    
                    # Save session to Supabase
                    saved_session = save_session_to_supabase(session_data)
                    
                    # Update user statistics
                    update_user_stats(user_id, session_data)
                    
                    # Upload analysis results to Supabase storage
                    try:
                        # Find all result files
                        result_files = glob.glob(os.path.join(parent_dir, 'generated_files', '*'))
                        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
                        
                        for file_path in result_files:
                            if os.path.isfile(file_path):
                                filename = os.path.basename(file_path)
                                # Skip temporary files
                                if not filename.startswith('tmp'):
                                    with open(file_path, 'rb') as f:
                                        file_data = f.read()
                                    
                                    # Determine bucket based on file type
                                    if filename.endswith('.mid'):
                                        bucket_name = 'analysis-results'
                                        storage_path = f"{user_id}/midi_{timestamp}_{filename}"
                                    elif filename.endswith('.json'):
                                        bucket_name = 'analysis-results'
                                        storage_path = f"{user_id}/report_{timestamp}_{filename}"
                                    elif filename.endswith('.png'):
                                        bucket_name = 'analysis-results'
                                        storage_path = f"{user_id}/visualization_{timestamp}_{filename}"
                                    elif filename.endswith('.txt'):
                                        bucket_name = 'analysis-results'
                                        storage_path = f"{user_id}/summary_{timestamp}_{filename}"
                                    else:
                                        continue
                                    
                                    # Upload to Supabase
                                    supabase.storage.from_(bucket_name).upload(
                                        path=storage_path,
                                        file=file_data,
                                        file_options={"content-type": "application/octet-stream"}
                                    )
                                    logger.info(f"Uploaded {filename} to Supabase bucket '{bucket_name}': {storage_path}")
                        
                    except Exception as e:
                        logger.warning(f"Failed to upload analysis results to Supabase: {e}")
                    
                    # Add session_id to response
                    analysis_result['session_id'] = saved_session['id'] if saved_session else None
                    
                    logger.info(f"Analysis completed successfully for user: {user_id}")
                    
                    return jsonify(analysis_result)
                else:
                    return jsonify({'error': 'Analysis completed but no report found'}), 500
            else:
                return jsonify({'error': 'Analysis pipeline failed'}), 500
                
        finally:
            # Clean up temporary files
            try:
                os.unlink(audio_path)
                os.unlink(sheet_path)
            except Exception as e:
                logger.warning(f"Failed to clean up temporary files: {e}")
    
    except Exception as e:
        logger.error(f"Analysis error: {str(e)}")
        return jsonify({'error': f'Analysis failed: {str(e)}'}), 500

@app.route('/users/<user_id>/sessions', methods=['GET'])
def get_user_sessions(user_id):
    """Get user sessions from Supabase"""
    try:
        if not supabase:
            logger.warning("Supabase not configured - returning empty sessions")
            return jsonify([])
            
        response = supabase.table('practice_sessions').select('*').eq('user_id', user_id).order('date', desc=True).execute()
        logger.info(f"Retrieved {len(response.data)} sessions for user: {user_id}")
        return jsonify(response.data)
    except Exception as e:
        logger.error(f"Error fetching sessions: {e}")
        return jsonify({'error': 'Failed to fetch sessions'}), 500

@app.route('/users/<user_id>/profile', methods=['GET'])
def get_user_profile(user_id):
    """Get user profile with statistics"""
    try:
        if not supabase:
            logger.warning("Supabase not configured - returning empty profile")
            return jsonify({'error': 'Supabase not configured'}), 500
            
        response = supabase.table('user_profiles').select('*').eq('id', user_id).execute()
        
        if response.data:
            user_profile = response.data[0]
            logger.info(f"User profile retrieved: {user_id}")
            return jsonify(user_profile)
        else:
            logger.warning(f"User profile not found: {user_id}")
            return jsonify({'error': 'User profile not found'}), 404
            
    except Exception as e:
        logger.error(f"Error fetching user profile: {e}")
        return jsonify({'error': 'Failed to fetch user profile'}), 500

@app.route('/users', methods=['POST'])
def create_user():
    """Create user in Supabase"""
    try:
        if not supabase:
            logger.warning("Supabase not configured - cannot create user")
            return jsonify({'error': 'Supabase not configured'}), 500
            
        data = request.get_json()
        user_id = data.get('id')
        
        if not user_id:
            return jsonify({'error': 'Missing user ID'}), 400
        
        # Create user profile
        user_profile = {
            'id': user_id,
            'total_sessions': 0,
            'total_practice_time': 0,
            'average_accuracy': 0,
            'best_accuracy': 0,
            'created_at': datetime.now().isoformat()
        }
        
        response = supabase.table('user_profiles').upsert(user_profile).execute()
        created_user = response.data[0] if response.data else None
        
        if created_user:
            logger.info(f"User created successfully: {user_id}")
            return jsonify({'message': 'User created successfully', 'user': created_user}), 201
        else:
            return jsonify({'error': 'Failed to create user'}), 500
            
    except Exception as e:
        logger.error(f"Error creating user: {e}")
        return jsonify({'error': 'Failed to create user'}), 500

@app.route('/users/<user_id>', methods=['GET'])
def get_user(user_id):
    """Get user from Supabase"""
    try:
        if not supabase:
            logger.warning("Supabase not configured - returning test user")
            return jsonify({'error': 'Supabase not configured'}), 500
            
        response = supabase.table('user_profiles').select('*').eq('id', user_id).execute()
        
        if response.data:
            user_profile = response.data[0]
            logger.info(f"User profile retrieved: {user_id}")
            return jsonify(user_profile)
        else:
            logger.warning(f"User not found: {user_id}")
            return jsonify({'error': 'User not found'}), 404
            
    except Exception as e:
        logger.error(f"Error fetching user: {e}")
        return jsonify({'error': 'Failed to fetch user'}), 500

if __name__ == '__main__':
    port = int(os.getenv('PORT', 8000))
    host = os.getenv('HOST', '0.0.0.0')
    
    logger.info(f"Starting GraceAI Production Server...")
    logger.info(f"Environment: {ENVIRONMENT}")
    logger.info(f"Server will be available at: http://{host}:{port}")
    logger.info(f"Health check: http://{host}:{port}/health")
    
    app.run(host=host, port=port, debug=DEBUG) 