"""
Sheet music processing service
Handles sheet music analysis using Audiveris and MuseScore
"""

import os
import subprocess
import logging
from typing import Optional, Dict, Any
from pathlib import Path

from app.core.config import settings

logger = logging.getLogger(__name__)


class SheetMusicProcessor:
    """Sheet music processing service"""
    
    def __init__(self):
        self.audiveris_path = settings.AUDIVERIS_PATH
        self.musescore_path = settings.MUSESCORE_PATH
    
    def process_sheet_music(self, image_path: str, output_dir: str) -> Dict[str, Any]:
        """
        Process sheet music image to MIDI
        
        Args:
            image_path: Path to sheet music image
            output_dir: Directory to save output files
            
        Returns:
            Dictionary with processing results
        """
        try:
            logger.info(f"Processing sheet music: {image_path}")
            
            # Ensure output directory exists
            os.makedirs(output_dir, exist_ok=True)
            
            # Process with Audiveris
            omr_result = self._process_with_audiveris(image_path, output_dir)
            
            if omr_result:
                # Convert to MIDI with MuseScore
                midi_result = self._convert_to_midi(omr_result, output_dir)
                
                return {
                    "success": True,
                    "omr_path": omr_result,
                    "midi_path": midi_result,
                    "message": "Sheet music processed successfully"
                }
            else:
                return {
                    "success": False,
                    "message": "Failed to process sheet music with Audiveris"
                }
                
        except Exception as e:
            logger.error(f"Sheet music processing error: {e}")
            return {
                "success": False,
                "message": f"Sheet music processing failed: {str(e)}"
            }
    
    def _process_with_audiveris(self, image_path: str, output_dir: str) -> Optional[str]:
        """Process image with Audiveris"""
        try:
            logger.info(f"Running Audiveris on: {image_path}")
            
            # Audiveris command
            cmd = [
                "java", "-jar", self.audiveris_path,
                "-batch",
                "-output", output_dir,
                image_path
            ]
            
            logger.info(f"Audiveris command: {' '.join(cmd)}")
            
            # Run Audiveris
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True,
                timeout=300  # 5 minutes timeout
            )
            
            logger.info(f"Audiveris completed successfully")
            logger.info(f"Audiveris stdout: {result.stdout}")
            
            # Look for generated files
            base_name = Path(image_path).stem
            possible_files = [
                os.path.join(output_dir, f"{base_name}.omr"),
                os.path.join(output_dir, f"{base_name}.mxl"),
                os.path.join(output_dir, f"{base_name}.xml")
            ]
            
            for file_path in possible_files:
                if os.path.exists(file_path):
                    logger.info(f"Found Audiveris output: {file_path}")
                    return file_path
            
            # Look for any generated files
            for file in os.listdir(output_dir):
                if file.endswith(('.omr', '.mxl', '.xml')):
                    found_path = os.path.join(output_dir, file)
                    logger.info(f"Found generated file: {found_path}")
                    return found_path
            
            logger.warning("No output files generated by Audiveris")
            return None
            
        except subprocess.TimeoutExpired:
            logger.error("Audiveris processing timed out")
            return None
        except subprocess.CalledProcessError as e:
            logger.error(f"Audiveris processing failed: {e}")
            logger.error(f"Audiveris stderr: {e.stderr}")
            return None
        except Exception as e:
            logger.error(f"Audiveris processing error: {e}")
            return None
    
    def _convert_to_midi(self, omr_path: str, output_dir: str) -> Optional[str]:
        """Convert OMR/MusicXML to MIDI using MuseScore"""
        try:
            logger.info(f"Converting to MIDI: {omr_path}")
            
            # Generate MIDI output path
            base_name = Path(omr_path).stem
            midi_path = os.path.join(output_dir, f"{base_name}.mid")
            
            # MuseScore command
            cmd = [
                self.musescore_path,
                "--export-to", midi_path,
                omr_path
            ]
            
            logger.info(f"MuseScore command: {' '.join(cmd)}")
            
            # Run MuseScore
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True,
                timeout=120  # 2 minutes timeout
            )
            
            logger.info(f"MuseScore completed successfully")
            logger.info(f"MuseScore stdout: {result.stdout}")
            
            if os.path.exists(midi_path):
                logger.info(f"MIDI file created: {midi_path}")
                return midi_path
            else:
                logger.warning("MIDI file not created by MuseScore")
                return None
                
        except subprocess.TimeoutExpired:
            logger.error("MuseScore conversion timed out")
            return None
        except subprocess.CalledProcessError as e:
            logger.error(f"MuseScore conversion failed: {e}")
            logger.error(f"MuseScore stderr: {e.stderr}")
            return None
        except Exception as e:
            logger.error(f"MuseScore conversion error: {e}")
            return None

